name: local_delivery_admin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  # BASE
  intl: ^0.17.0
  html: ^0.15.0
  shared_preferences: ^2.0.15
  google_fonts: ^2.3.3

  # CONNECTIVITY
  http: ^0.13.4
  connectivity_plus: ^2.3.0

  # STATE MANAGEMENT
  mobx: ^2.0.7+2
  flutter_mobx: ^2.0.6+1

  # TOAST
  fluttertoast: ^8.0.9

  # IMAGE
  cached_network_image: ^3.2.1
  image_picker: ^0.8.5+3

  # UI
  lottie: ^1.3.0
  fl_chart: ^0.50.6
  charts_flutter: ^0.12.0
  syncfusion_flutter_charts: ^20.1.56
  flutter_switch: ^0.3.2

  # COUNTRY
  country_code_picker: ^2.0.2

  # PACKAGE INFO
  package_info_plus: ^1.4.2

  # LUNCH URL
  url_launcher: ^6.1.2

  # FIREBASE
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1

  # TIMELINE
  timeline_tile: ^2.0.0

  # DATE TIME PICKER
  date_time_picker: ^2.1.0

  elegant_notification: ^1.5.4

  # CURRENCY PICKER
  currency_picker: ^2.0.11

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7
  #flutter packages pub run build_runner build --delete-conflicting-outputs

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/flag/

